# Sistema_Salud
Proyectos desarrollados en Netbeans
package mantenedor;

/**
 *
 * @author Cristian
 */
public class mantenedorSalud extends javax.swing.JFrame {

    /**
     * Creates new form mantenedorSalud
     */
    frameAccion manSalud;
    Reporte repor;
    
    public mantenedorSalud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAccion = new javax.swing.JMenu();
        jmiIngresar = new javax.swing.JMenuItem();
        jmiEliminar = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmReporte = new javax.swing.JMenu();
        jmiReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas de horas - Chantalud");
        setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Sistema de Horas");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel2.setText("Salud");

        jLabel3.setText("By CastilloSoza");

        jmAccion.setText("Acción");

        jmiIngresar.setText("Ingresar Hora");
        jmiIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIngresarActionPerformed(evt);
            }
        });
        jmAccion.add(jmiIngresar);

        jmiEliminar.setText("Cancelar Hora");
        jmiEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarActionPerformed(evt);
            }
        });
        jmAccion.add(jmiEliminar);

        jmiSalir.setText("Salir");
        jmAccion.add(jmiSalir);

        jMenuBar1.add(jmAccion);

        jmReporte.setText("Reporte");

        jmiReporte.setText("Horas agendadas");
        jmiReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReporteActionPerformed(evt);
            }
        });
        jmReporte.add(jmiReporte);

        jMenuBar1.add(jmReporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        setBounds(0, 0, 416, 338);
    }// </editor-fold>                        

    private void jmiIngresarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        manSalud = new frameAccion(1);
        manSalud.setVisible(true);
        manSalud.pack();
        manSalud.setLocationRelativeTo(this);
    }                                           

    private void jmiEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
        manSalud = new frameAccion(2);
        manSalud.setVisible(true);
        manSalud.pack();
        manSalud.setLocationRelativeTo(this);
    }                                           

    private void jmiReporteActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
         repor = new Reporte();
        repor.setVisible(true);
        repor.pack();
        repor.setLocationRelativeTo(this);
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mantenedorSalud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mantenedorSalud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mantenedorSalud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mantenedorSalud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mantenedorSalud().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAccion;
    private javax.swing.JMenu jmReporte;
    private javax.swing.JMenuItem jmiEliminar;
    private javax.swing.JMenuItem jmiIngresar;
    private javax.swing.JMenuItem jmiReporte;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration                   
}
